name: ☁ Headless Builds
on: [push, pull_request]


jobs:
  mac-editor:
    runs-on: "macos-latest"
    name: macOS Headless (target=release_debug, tools=yes)
  env:
    GODOT_VERSION: 3.3
    
    steps:
      - name: Test
        run: mkdir Godot-${GODOT_VERSION}

