name: ☁ Headless Builds
on: [push, pull_request]

# Global Cache Settings
env:
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: platform=server verbose=yes warnings=all werror=yes debug_symbols=no --jobs=2


jobs:
  mac-editor:
    runs-on: "macos-latest"
    name: macOS Headless (target=release_debug, tools=yes)

    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Check if brew is installed
        run: brew